AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda local hello

Resources:
  SayHelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.sayHello
      Runtime: nodejs14.x
      CodeUri: ./src
      # Para permitir el acceso a la BD
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StorageHello

      # Para acceder
      Environment:
        Variables:
          TABLE: !Ref StorageHello
          APP-STAGE: local

      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
  
  StorageHello:
    Type: 'AWS::Serverless::SimpleTable'
        
Outputs:
  WorldApi:
    Description: "Cool API"
    value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello/"